# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: cdk
    before: |
      npm i -g aws-cdk 
  # https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
  - name: terraform
    before: |
      ./bin/terraform_cli_install.sh
  # random utilities
  - name: utils
    before: |
      sudo apt-get install tree
  # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      ./bin/aws_cli_install.sh



# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
