# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'aws-sdk-s3'
gem 'pry' # for debugging
gem 'nokogiri' # parsing

# 'bundle init' to create Gemfile 
# 'bundle install' to download gems (packages)